import Head from 'next/head';
import NavbarTrans from '../../components/navbarTrans';

export default function editProfil() {
    return (
        <div>
            <Head>
                <title>Edit Profil</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <NavbarTrans title="Edit Profil" />
            <div className="p-5">
                <div className="field">
                    <label className="label">Nama</label>
                    <div className="control">
                        <input className="input" type="text" placeholder="Nama" />
                    </div>
                </div>
                <div className="field">
                    <label className="label">Alamat</label>
                    <div className="control">
                        <textarea className="textarea" placeholder="Alamat"></textarea>
                    </div>
                </div>
                <div className="field">
                    <label className="label">Kecamatan</label>
                    <div className="control">
                        <div className="select">
                            <select>
                                <option>Pilih Kecamatan</option>
                                <option>Banyuwangi</option>
                                <option>Gambiran</option>
                                <option>Glagah</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div className="field">
                    <label className="label">Desa</label>
                    <div className="control">
                        <div className="select">
                            <select>
                                <option>Pilih Desa</option>
                                <option>Gambiran</option>
                                <option>Glagah</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="file has-name py-5">
                    <label class="file-label">
                        <input class="file-input" type="file" name="resume" />
                        <span class="file-cta">
                            <span class="file-icon">
                                <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Pilih Foto…
                            </span>
                        </span>
                        <span class="file-name">
                            images.png
                        </span>
                    </label>
                </div>
                <div className="buttons has-addons is-right">
                    <button className="button btn-main">
                        Simpan
                    </button>
                </div>
            </div>
        </div>
    )
}