import Head from 'next/head'
import CardWlijo from '../components/cardWlijo'
import Carousel from '../components/carousel'
import styles from '../styles/Home.module.css'
import wlijos from '../public/wlijo.json'
import products from '../public/product.json'
import testimonyes from '../public/testimony.json'
import CardProduct from '../components/cardProduct'
import CardTestimony from '../components/cardTestimony'
import MainLayout from '../layouts/mainLayout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MainLayout>
        {/* carousel */}
        <Carousel />
        {/* search location*/}
        <div className='wrap is-flex is-align-items-center is-flex-direction-column is-hidden-tablet'>
          <p className='green is-size-5 has-text-weight-medium mb-2'>Lokasi</p>
          <div className="select">
            <select>
              <option>Select dropdown</option>
              <option>With options</option>
            </select>
          </div>
        </div>
        {/* card Wlijo */}
        <div className="wrap py-4 is-flex is-justify-content-space-between is-align-items-center">
          <p className='green is-size-5 has-text-weight-medium'>Wlijo Terdekat</p>
          <p className='green is-size-6'>Lebih Banyak</p>
        </div>
        <div className=' pb-5 is-flex outer-card is-justify-content-space-between'>
          {
            wlijos.map((wlijo, index) => (
              <CardWlijo key={index} data={wlijo} />
            ))
          }

        </div>


        {/* card Produk */}
        <div className="wrap py-4 is-flex is-justify-content-space-between is-align-items-center">
          <p className='green is-size-5 has-text-weight-medium'>Terlaris</p>
          <p className='green is-size-6'>Lebih Banyak</p>
        </div>
        <div className=' pb-5 is-flex outer-card is-justify-content-space-between'>
          {
            products.map((product, index) => (
              <CardProduct key={index} data={product} />
            ))
          }
        </div>

        {/* tertimoni */}
        <p className='py-4 wrap green is-size-5 has-text-weight-medium'>Testimoni</p>
        <div className=' pb-5 testimoni-wrap  is-flex is-flex-wrap-wrap wrap is-justify-content-space-between'>
          {
            testimonyes.map((testymony, index) => (
              <CardTestimony key={index} data={testymony} />
            ))
          }
        </div>
      </MainLayout>
    </div>
  )
}
